# Generated by Django 5.2.3 on 2025-06-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_favorites_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cart',
            new_name='shopping_cart',
        ),
    ]
