name: Foodgram CI/CD

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: adelsalamov
          POSTGRES_PASSWORD: qwerty123456
          POSTGRES_DB: db_foodgram
        ports: [5432:5432]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.11"
      - run: |
          pip install --upgrade pip ruff==0.8.0
          pip install -r backend/requirements.txt
      - run: |
          ruff check backend/
          cd backend && python manage.py test
        env:
          POSTGRES_USER: adelsalamov
          POSTGRES_PASSWORD: qwerty123456
          POSTGRES_DB: db_foodgram
          DB_HOST: localhost
          DB_PORT: 5432

  build_and_push:
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [backend, frontend, infra]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.component }}/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_${{ matrix.component }}:latest